_DISCLAIMERS = {
    "US": (
        "\n\n⚠️ Disclaimer: This analysis is generated by AI and does not constitute licensed "
        "financial, tax, or legal advice. Past performance does not guarantee future results. "
        "Please consult a Certified Financial Planner (CFP) and qualified tax advisor before "
        "making financial decisions. FinSight AI is not a registered investment advisor under "
        "the SEC Investment Advisers Act."
    ),
    "UK": (
        "\n\n⚠️ Disclaimer: This analysis is generated by AI and does not constitute regulated "
        "financial advice under the Financial Services and Markets Act 2000. Past performance is "
        "not a reliable indicator of future results. Please consult an FCA-authorised financial "
        "adviser before making investment decisions."
    ),
    "EU": (
        "\n\n⚠️ Disclaimer: This analysis is generated by AI and does not constitute investment "
        "advice within the meaning of MiFID II. Past performance is not a reliable indicator of "
        "future results. Please consult a qualified financial advisor before making investment "
        "decisions."
    ),
}

_DEFAULT = _DISCLAIMERS["US"]

_LOCATION_TO_JURISDICTION = {
    "UK": "UK", "England": "UK", "Scotland": "UK", "Wales": "UK",
    "Germany": "EU", "France": "EU", "Italy": "EU", "Spain": "EU",
    "Netherlands": "EU", "Belgium": "EU", "Sweden": "EU", "Poland": "EU",
}


def get_disclaimer(jurisdiction: str = "US") -> str:
    return _DISCLAIMERS.get(jurisdiction, _DEFAULT)


def detect_jurisdiction(location: str) -> str:
    """Infer jurisdiction from a location string."""
    for keyword, jurisdiction in _LOCATION_TO_JURISDICTION.items():
        if keyword.lower() in location.lower():
            return jurisdiction
    return "US"


def inject_disclaimer(text: str, location: str = "") -> str:
    """Append the correct jurisdiction disclaimer to any text block."""
    jurisdiction = detect_jurisdiction(location) if location else "US"
    return text + get_disclaimer(jurisdiction)
