"""
/report endpoints

POST /report/generate  — accepts canonical final_report JSON, returns PDF bytes
"""

import io
from datetime import datetime
from typing import Any
from fastapi import APIRouter
from fastapi.responses import Response
from pydantic import BaseModel

router = APIRouter()


class ReportRequest(BaseModel):
    final_report: dict
    session_id: str = "unknown"


# ── ReportLab PDF generation ──────────────────────────────────────────────────

def _safe(val: Any, default: str = "—") -> str:
    if val is None:
        return default
    if isinstance(val, float):
        return f"{val:,.2f}"
    return str(val)


def _pct(val: Any) -> str:
    if val is None:
        return "—"
    try:
        return f"{float(val):.1f}%"
    except Exception:
        return str(val)


def _usd(val: Any) -> str:
    if val is None:
        return "—"
    try:
        return f"${float(val):,.0f}"
    except Exception:
        return str(val)


def generate_pdf(report: dict, session_id: str) -> bytes:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable, PageBreak,
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    BRAND = colors.HexColor("#F59E0B")
    DARK = colors.HexColor("#0A0F1E")
    GREY = colors.HexColor("#6B7280")
    LIGHT = colors.HexColor("#F3F4F6")

    h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=22, textColor=DARK, spaceAfter=6)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=14, textColor=DARK, spaceAfter=4, spaceBefore=12)
    h3 = ParagraphStyle("H3", parent=styles["Heading3"], fontSize=11, textColor=BRAND, spaceAfter=3, spaceBefore=8)
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, leading=14, spaceAfter=4)
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=GREY, leading=12)
    center = ParagraphStyle("Center", parent=styles["Normal"], fontSize=9, alignment=TA_CENTER)

    elements = []

    # ── Cover ─────────────────────────────────────────────────────────────────
    overview = report.get("overview") or {}
    session = report.get("session") or {}

    elements.append(Spacer(1, 0.5 * inch))
    elements.append(Paragraph("FinSight AI", h1))
    elements.append(Paragraph("Personal Financial Intelligence Report", ParagraphStyle(
        "Sub", parent=styles["Normal"], fontSize=14, textColor=GREY, spaceAfter=4
    )))
    elements.append(HRFlowable(width="100%", thickness=2, color=BRAND, spaceAfter=10))

    meta_data = [
        ["Generated:", datetime.now().strftime("%B %d, %Y")],
        ["Session ID:", session.get("session_id", session_id)],
        ["Location:", session.get("location", "—")],
        ["Age:", _safe(session.get("age"))],
        ["Risk Tolerance:", str(session.get("risk_tolerance", "—")).title()],
        ["Investment Horizon:", f"{session.get('investment_horizon_years', '—')} years"],
    ]
    t = Table(meta_data, colWidths=[1.5 * inch, 4 * inch])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), GREY),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.3 * inch))

    elements.append(Paragraph(
        "DISCLAIMER: This report is generated by an AI multi-agent system for educational purposes only. "
        "It does not constitute licensed financial, investment, tax, or legal advice. "
        "Please consult qualified professionals before making financial decisions.",
        small,
    ))
    elements.append(PageBreak())

    # ── Financial Health Overview ─────────────────────────────────────────────
    elements.append(Paragraph("Financial Health Overview", h2))
    elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT, spaceAfter=8))

    health_data = [
        ["Metric", "Value", "Benchmark", "Status"],
        ["Health Score", f"{overview.get('health_score', 0):.1f}/100 ({overview.get('health_grade', '—')})", "≥ 65 (B)", ""],
        ["Monthly Income", _usd(overview.get("monthly_income")), "—", ""],
        ["Monthly Expenses", _usd(overview.get("monthly_expenses")), "—", ""],
        ["Monthly Surplus", _usd(overview.get("monthly_surplus")), "> $0", ""],
        ["Savings Rate", _pct(overview.get("savings_rate")), "≥ 20%", ""],
        ["Debt-to-Income", _pct(overview.get("debt_to_income")), "≤ 36%", ""],
        ["Emergency Fund", f"{overview.get('emergency_fund_months', 0):.1f} months", "≥ 6 months", ""],
        ["Net Worth", _usd(overview.get("net_worth")), "—", ""],
    ]
    t = Table(health_data, colWidths=[2.2 * inch, 1.6 * inch, 1.6 * inch, 1.2 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.25, GREY),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.2 * inch))

    # ── Budget Analysis ───────────────────────────────────────────────────────
    budget = report.get("budget") or {}
    if budget:
        elements.append(Paragraph("Budget Analysis", h2))
        elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT, spaceAfter=6))
        fw = budget.get("recommended_framework", "—")
        elements.append(Paragraph(f"<b>Framework:</b> {str(fw).replace('_', ' ').upper()}", body))

        top_cuts = budget.get("top_cuts") or []
        if top_cuts:
            elements.append(Paragraph("Top Cost Reduction Opportunities", h3))
            for i, cut in enumerate(top_cuts[:5], 1):
                elements.append(Paragraph(f"{i}. {cut}", body))

        actions = budget.get("action_plan_90_days") or budget.get("action_items") or []
        if actions:
            elements.append(Paragraph("90-Day Action Plan", h3))
            for i, action in enumerate(actions[:5], 1):
                elements.append(Paragraph(f"{i}. {action}", body))

    # ── Investment Strategy ───────────────────────────────────────────────────
    inv = report.get("investment") or {}
    if inv:
        elements.append(Paragraph("Investment Strategy", h2))
        elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT, spaceAfter=6))

        alloc = inv.get("allocation") or {}
        if alloc:
            alloc_data = [["Asset Class", "Allocation"]]
            for asset, pct in alloc.items():
                alloc_data.append([asset.replace("_", " ").title(), f"{pct}%"])
            t = Table(alloc_data, colWidths=[3 * inch, 2 * inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), DARK),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
                ("GRID", (0, 0), (-1, -1), 0.25, GREY),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(t)
            elements.append(Spacer(1, 0.15 * inch))

        if inv.get("market_context"):
            ctx = inv["market_context"]
            elements.append(Paragraph("Market Context", h3))
            if isinstance(ctx, dict):
                for k, v in ctx.items():
                    elements.append(Paragraph(f"<b>{k.replace('_', ' ').title()}:</b> {v}", body))
            elif isinstance(ctx, str):
                elements.append(Paragraph(ctx, body))

    # ── Goal Roadmap ──────────────────────────────────────────────────────────
    goals = report.get("goals") or {}
    if goals:
        elements.append(Paragraph("Goal Roadmap", h2))
        elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT, spaceAfter=6))
        computed = goals.get("computed_goals") or []
        if computed:
            goal_data = [["Goal", "Target", "Timeline", "Required/mo", "Feasibility"]]
            for g in computed:
                goal_data.append([
                    g.get("description", "—")[:40],
                    _usd(g.get("target_amount")),
                    f"{g.get('timeline_months', '—')} mo",
                    _usd(g.get("required_monthly_contribution")),
                    f"{g.get('feasibility_score', 0):.0f}%",
                ])
            t = Table(goal_data, colWidths=[2.2 * inch, 1.1 * inch, 0.9 * inch, 1.1 * inch, 1 * inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), DARK),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
                ("GRID", (0, 0), (-1, -1), 0.25, GREY),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("WORDWRAP", (0, 0), (-1, -1), True),
            ]))
            elements.append(t)

    # ── Debt Elimination ──────────────────────────────────────────────────────
    debt = report.get("debt") or {}
    if debt:
        elements.append(Paragraph("Debt Elimination Plan", h2))
        elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT, spaceAfter=6))
        method = str(debt.get("recommended_method", "—")).title()
        elements.append(Paragraph(f"<b>Recommended Strategy:</b> {method}", body))
        total_debt = debt.get("total_debt_balance")
        if total_debt:
            elements.append(Paragraph(f"<b>Total Debt:</b> {_usd(total_debt)}", body))
        sims = debt.get("simulations") or {}
        selected = sims.get(debt.get("recommended_method", "avalanche")) or {}
        if selected:
            elements.append(Paragraph(
                f"<b>Months to Debt-Free:</b> {selected.get('months_to_debt_free', '—')} | "
                f"<b>Interest Saved vs. Minimum-Only:</b> {_usd(selected.get('interest_saved_vs_minimum'))}",
                body,
            ))
        explanation = debt.get("strategy_explanation") or debt.get("payoff_timeline_narrative")
        if explanation:
            elements.append(Paragraph(str(explanation), body))

    # ── Tax Optimization ──────────────────────────────────────────────────────
    tax = report.get("tax") or {}
    if tax:
        elements.append(Paragraph("Tax Optimization", h2))
        elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT, spaceAfter=6))
        mbkt = tax.get("marginal_bracket_pct") or (tax.get("precomputed_metrics") or {}).get("marginal_bracket_pct")
        etr = tax.get("effective_rate_pct") or (tax.get("precomputed_metrics") or {}).get("effective_rate_estimate_pct")
        if mbkt is not None or etr is not None:
            elements.append(Paragraph(
                f"<b>Marginal Bracket:</b> {mbkt if mbkt is not None else '—'}% | "
                f"<b>Effective Rate Est.:</b> {etr if etr is not None else '—'}%",
                body,
            ))
        opportunities = tax.get("opportunities") or tax.get("tax_optimization_opportunities") or []
        if opportunities:
            elements.append(Paragraph("Optimization Opportunities", h3))
            opp_data = [["Opportunity", "Est. Annual Savings", "Priority"]]
            for opp in opportunities[:6]:
                if isinstance(opp, dict):
                    savings = opp.get("annual_savings") or opp.get("annual_savings_potential")
                    name = opp.get("name") or opp.get("action") or "—"
                    opp_data.append([
                        str(name)[:45],
                        _usd(savings),
                        str(opp.get("priority", "—")),
                    ])
            if len(opp_data) > 1:
                t = Table(opp_data, colWidths=[3.2 * inch, 1.5 * inch, 1.5 * inch])
                t.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), DARK),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
                    ("GRID", (0, 0), (-1, -1), 0.25, GREY),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]))
                elements.append(t)

    # ── Personalised Advice ───────────────────────────────────────────────────
    advice = report.get("personalised_advice") or {}
    if advice:
        elements.append(PageBreak())
        elements.append(Paragraph("Personalised Financial Advice", h2))
        elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT, spaceAfter=6))

        summary = advice.get("executive_summary")
        if summary:
            elements.append(Paragraph(str(summary), body))
            elements.append(Spacer(1, 0.1 * inch))

        actions = advice.get("priority_actions") or []
        if actions:
            elements.append(Paragraph("Priority Actions", h3))
            for action in actions[:7]:
                if isinstance(action, dict):
                    elements.append(Paragraph(
                        f"<b>[{action.get('rank', '')}] {action.get('action', '')}</b> "
                        f"({action.get('domain', '')} | {action.get('timeline', '')})",
                        body,
                    ))
                    if action.get("rationale"):
                        elements.append(Paragraph(str(action["rationale"]), small))
                elif isinstance(action, str):
                    elements.append(Paragraph(action, body))

        checklist = advice.get("next_30_day_checklist") or []
        if checklist:
            elements.append(Paragraph("Next 30-Day Checklist", h3))
            for i, item in enumerate(checklist[:10], 1):
                elements.append(Paragraph(f"☐  {i}. {item}", body))

    # ── Stress Tests ──────────────────────────────────────────────────────────
    stress = report.get("stress_tests") or {}
    if stress:
        elements.append(Paragraph("Stress Test Results", h2))
        elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT, spaceAfter=6))
        summary_st = stress.get("summary") or {}
        if summary_st:
            elements.append(Paragraph(
                f"<b>Overall Resilience:</b> {summary_st.get('overall_resilience', '—')} | "
                f"<b>Average Score:</b> {summary_st.get('average_score', '—')}/10 | "
                f"<b>Weakest Scenario:</b> {str(summary_st.get('weakest_scenario', '—')).replace('_', ' ')}",
                body,
            ))
        scenarios = stress.get("scenarios") or {}
        if scenarios:
            sc_data = [["Scenario", "Score", "Assessment"]]
            for sc_key, sc in scenarios.items():
                if isinstance(sc, dict):
                    sc_data.append([
                        sc_key.replace("_", " ").title(),
                        f"{sc.get('score', '—')}/10",
                        sc.get("assessment", "—"),
                    ])
            if len(sc_data) > 1:
                t = Table(sc_data, colWidths=[2.5 * inch, 1 * inch, 2.8 * inch])
                t.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), DARK),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
                    ("GRID", (0, 0), (-1, -1), 0.25, GREY),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]))
                elements.append(t)

    # ── Final Disclaimer ──────────────────────────────────────────────────────
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT, spaceAfter=8))
    elements.append(Paragraph("Methodology & Disclaimer", h3))
    elements.append(Paragraph(
        "This report was generated by FinSight AI, a multi-agent AI financial intelligence platform. "
        "Financial metrics (savings rate, DTI, emergency fund, net worth, health score) are computed deterministically "
        "using Python with numpy-financial. Market data is sourced from yfinance and FRED API (Federal Reserve). "
        "LLM-generated narrative analysis uses Gemini / Llama models via API. "
        "All recommendations are for educational analysis only and do not constitute licensed financial, "
        "investment, tax, or legal advice. Past performance does not guarantee future results. "
        "Consult a qualified financial professional before making financial decisions.",
        small,
    ))

    doc.build(elements)
    buf.seek(0)
    return buf.read()


# ── Route ─────────────────────────────────────────────────────────────────────

@router.post("/generate")
async def generate_report(request: ReportRequest):
    """
    Accepts the canonical final_report JSON and returns a polished PDF.
    Returns Content-Disposition: attachment for browser download.
    """
    try:
        pdf_bytes = generate_pdf(request.final_report, request.session_id)
    except ImportError:
        from fastapi import HTTPException
        raise HTTPException(
            status_code=503,
            detail="PDF generation unavailable: install reportlab (pip install reportlab)",
        )
    except Exception as e:
        from fastapi import HTTPException
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {str(e)[:200]}")

    filename = f"finsight_report_{request.session_id[:8]}.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
